### ISSUE TITLE
Why does mimer preferGlobal?

### ISSUE THREAD

**Issue by mikelambert** [data-uri/mimer#1]
When I install mimer, it triggers the following warning:
```
npm WARN prefer global mimer@0.2.1 should be installed with -g
```

I'm installing mimer because it's an n-level deep dependency:
```
└─┬ mjml@3.3.2
  └─┬ mjml-core@3.3.2
    └─┬ juice@4.1.0
      └─┬ web-resource-inliner@4.1.0
        └─┬ datauri@1.0.5
          └── mimer@0.2.1 
```

Why does mimer preferGlobal and trigger errors? It's use seems to date from the first commit...

**Comment by heldr** [comment]
I believe it triggers warn, doesn't it?

But good point, `preferGlobal` shouldn't be flagged as true tho.

**Comment by mikelambert** [comment]
Err sorry, trigger warnings! (First sentence got it right, last sentence got it wrong.) Thanks for the fix!

**Comment by heldr** [comment]
You're very welcome 🍵 

@mikelambert PS: I'll be testing datauri with webpack later this week.
